/**
 * @fileoverview Generates signer fixtures at test time
 *
 * Nothing key-shaped is committed to the repository. An earlier version checked
 * in `tests/fixtures/agent.key`, which `.gitignore` (`*.key`) silently refused
 * to track — so the test passed on the machine that created the file and failed
 * on every clean checkout. CI caught it on its first ever run.
 *
 * Rather than weaken the ignore rule, the fixtures are built into a temp
 * directory when the tests run. The upside beyond correctness: the repo contains
 * no private keys, no keystores and no keystore passwords, so there is nothing to
 * mistake for a real credential and nothing for a scanner to flag.
 *
 * The key below is Hardhat/Anvil's well-known account #1. It is public by
 * design, has never held value on any network, and is used here only to derive a
 * deterministic address to assert against.
 */

import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createCipheriv, pbkdf2Sync, randomBytes, scryptSync } from "node:crypto";
import { keccak256 } from "viem";
import { privateKeyToAccount } from "viem/accounts";

/** Hardhat/Anvil account #1. Public, unfunded, deterministic. */
export const TEST_KEY = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d";

/** The address TEST_KEY derives to. */
export const TEST_ADDRESS = privateKeyToAccount(TEST_KEY).address;

export const KEYSTORE_PASSWORD = "test-password";

export interface SignerFixtures {
  dir: string;
  /** Hex key in a file, with a trailing newline, as a real key file has. */
  keyFile: string;
  /** V3 keystore using scrypt. */
  keystoreScrypt: string;
  /** V3 keystore using pbkdf2. */
  keystorePbkdf2: string;
  /** Password file with a trailing newline, as a real one has. */
  passwordFile: string;
  /** Module whose default export returns a usable viem LocalAccount. */
  signerModule: string;
  /** Module returning an account that cannot sign an EIP-7702 authorization. */
  signerModuleBad: string;
}

/**
 * Builds a V3 keystore (Web3 Secret Storage) around TEST_KEY.
 *
 * scrypt parameters are deliberately weaker than geth's defaults (N=8192 rather
 * than 262144) so the suite stays fast. The decryption path under test does not
 * care which parameters were used — it reads them from the file.
 */
function buildKeystore(kdf: "scrypt" | "pbkdf2", password: string): string {
  const privateKey = Buffer.from(TEST_KEY.slice(2), "hex");
  const salt = randomBytes(32);
  const iv = randomBytes(16);
  const secret = Buffer.from(password, "utf8");

  let derived: Buffer;
  let kdfparams: Record<string, unknown>;

  if (kdf === "scrypt") {
    const N = 8192;
    const r = 8;
    const p = 1;
    derived = scryptSync(secret, salt, 32, { N, r, p, maxmem: 256 * N * r });
    kdfparams = { dklen: 32, n: N, p, r, salt: salt.toString("hex") };
  } else {
    const c = 10000;
    derived = pbkdf2Sync(secret, salt, c, 32, "sha256");
    kdfparams = { c, dklen: 32, prf: "hmac-sha256", salt: salt.toString("hex") };
  }

  const cipher = createCipheriv("aes-128-ctr", derived.subarray(0, 16), iv);
  const ciphertext = Buffer.concat([cipher.update(privateKey), cipher.final()]);

  // MAC covers the second half of the derived key plus the ciphertext.
  const mac = keccak256(
    Buffer.concat([derived.subarray(16, 32), ciphertext]) as never
  ).slice(2);

  return JSON.stringify(
    {
      version: 3,
      address: TEST_ADDRESS.slice(2).toLowerCase(),
      crypto: {
        cipher: "aes-128-ctr",
        ciphertext: ciphertext.toString("hex"),
        cipherparams: { iv: iv.toString("hex") },
        kdf,
        kdfparams,
        mac,
      },
    },
    null,
    2
  );
}

const SIGNER_MODULE = `// Generated by tests/helpers/signer-fixtures.ts
import { privateKeyToAccount } from "viem/accounts";

export default async function createAccount() {
  return privateKeyToAccount("${TEST_KEY}");
}
`;

/**
 * A signer that can sign typed data but not an EIP-7702 authorization — the
 * realistic failure mode of a custody adapter predating 7702. It has to be
 * rejected when the signer resolves, not halfway through a sweep.
 */
const SIGNER_MODULE_BAD = `// Generated by tests/helpers/signer-fixtures.ts
export default function createAccount() {
  return {
    address: "${TEST_ADDRESS}",
    signTypedData: async () => "0x",
    // signAuthorization deliberately absent
  };
}
`;

/** Writes every fixture into a fresh temp directory and returns their paths. */
export function createSignerFixtures(): SignerFixtures {
  const dir = mkdtempSync(join(tmpdir(), "zerodust-signer-"));

  const write = (name: string, contents: string) => {
    const path = join(dir, name);
    // 0600 on anything key-shaped, matching how a real operator should store it.
    writeFileSync(path, contents, { mode: name.endsWith(".mjs") ? 0o644 : 0o600 });
    return path;
  };

  return {
    dir,
    // Trailing newlines on purpose: they are near-universal in real files and
    // the reader has to tolerate them.
    keyFile: write("agent.key", `${TEST_KEY}\n`),
    keystoreScrypt: write("keystore-scrypt.json", buildKeystore("scrypt", KEYSTORE_PASSWORD)),
    keystorePbkdf2: write("keystore-pbkdf2.json", buildKeystore("pbkdf2", KEYSTORE_PASSWORD)),
    passwordFile: write("password.txt", `${KEYSTORE_PASSWORD}\n`),
    signerModule: write("signer-module.mjs", SIGNER_MODULE),
    signerModuleBad: write("signer-module-bad.mjs", SIGNER_MODULE_BAD),
  };
}
